import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Navigation, HashNavigation } from "swiper";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const slides = [1, 2, 3, 4];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Swiper
          spaceBetween={30}
          hashNavigation={{
            watchState: true,
          }}
          pagination={{
            clickable: true,
          }}
          navigation={true}
          modules={[Pagination, Navigation, HashNavigation]}
          className="mySwiper"
        >
          {
            slides.map((idx) => {
              return (
                <SwiperSlide data-hash={`slide${idx}`} key={idx}>
                  <figure className="relative flex justify-center">
                    <img src={`/img/slide/${idx}.jpg`} alt="slide" className="slide-image"/>
                    <figcaption className="absolute top-1/2 text-gray-600 text-[70px] font-bold">Crypto E-Vote</figcaption>
                  </figure>
                </SwiperSlide>
              )
            })
          }
        </Swiper>
      </main>
    </>
  )
}
